apiVersion: v1
kind: Secret
metadata:
  name: dubverse-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: "myproductionjwtsecretpleasechange!!!"
  OPENAI_API_KEY: "sk-proj-mockopenaiapikey!!!"
  GEMINI_API_KEY: "mockgeminiapikey!!!"
  AWS_ACCESS_KEY_ID: "mockawsaccesskey!!!"
  AWS_SECRET_ACCESS_KEY: "mockawssecretaccesskey!!!"
